export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    me: '/auth/me',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  leads: {
    list: '/leads',
    create: '/leads',
    detail: (id: string) => `/leads/${id}`,
    update: (id: string) => `/leads/${id}`,
    delete: (id: string) => `/leads/${id}`,
    activities: (id: string) => `/leads/${id}/activities`,
    kanban: '/leads/kanban',
    bulkUpdate: '/leads/bulk',
  },
  campaigns: {
    list: '/campaigns',
    create: '/campaigns',
    detail: (id: string) => `/campaigns/${id}`,
    update: (id: string) => `/campaigns/${id}`,
    delete: (id: string) => `/campaigns/${id}`,
    metrics: (id: string) => `/campaigns/${id}/metrics`,
    sync: (id: string) => `/campaigns/${id}/sync`,
  },
  ai: {
    chat: '/ai/chat',
    stream: '/ai/stream',
    insights: '/ai/insights',
    leadScore: (id: string) => `/ai/leads/${id}/score`,
    suggestions: '/ai/suggestions',
    conversations: '/ai/conversations',
  },
  whatsapp: {
    conversations: '/whatsapp/conversations',
    messages: (conversationId: string) => `/whatsapp/conversations/${conversationId}/messages`,
    send: '/whatsapp/send',
    templates: '/whatsapp/templates',
  },
  finance: {
    transactions: '/finance/transactions',
    invoices: '/finance/invoices',
    invoiceDetail: (id: string) => `/finance/invoices/${id}`,
    subscription: '/finance/subscription',
    summary: '/finance/summary',
  },
  analytics: {
    dashboard: '/analytics/dashboard',
    leads: '/analytics/leads',
    campaigns: '/analytics/campaigns',
    revenue: '/analytics/revenue',
  },
  team: {
    members: '/team/members',
    invite: '/team/invite',
    member: (id: string) => `/team/members/${id}`,
  },
  settings: {
    profile: '/settings/profile',
    company: '/settings/company',
    integrations: '/settings/integrations',
    notifications: '/settings/notifications',
  },
} as const
